"""column name changed

Revision ID: 345d50c23ef3
Revises: b962ca6bae4f
Create Date: 2026-02-07 13:48:32.142400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '345d50c23ef3'
down_revision = 'b962ca6bae4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyEmail', sa.String(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_master_admins_compaEmail'))
        batch_op.create_index(batch_op.f('ix_master_admins_companyEmail'), ['companyEmail'], unique=True)
        batch_op.drop_column('compaEmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compaEmail', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_master_admins_companyEmail'))
        batch_op.create_index(batch_op.f('ix_master_admins_compaEmail'), ['compaEmail'], unique=True)
        batch_op.drop_column('companyEmail')

    # ### end Alembic commands ###
