"""empty message

Revision ID: e4cb33c9e51e
Revises: 345d50c23ef3
Create Date: 2026-02-09 15:04:26.144387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4cb33c9e51e'
down_revision = '345d50c23ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('company_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('company_address', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_master_admins_companyEmail'))
        batch_op.create_index(batch_op.f('ix_master_admins_company_email'), ['company_email'], unique=True)
        batch_op.drop_column('lastName')
        batch_op.drop_column('companyPhone')
        batch_op.drop_column('middleName')
        batch_op.drop_column('companyAddress')
        batch_op.drop_column('companyName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('companyEmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyEmail', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('companyName', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('companyAddress', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('middleName', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('companyPhone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_master_admins_company_email'))
        batch_op.create_index(batch_op.f('ix_master_admins_companyEmail'), ['companyEmail'], unique=True)
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_email')
        batch_op.drop_column('company_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
